# Generated by Django 6.0.5 on 2026-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockinterviewsession",
            name="vapi_assistant_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
